### PR TITLE
Update fedora build to version 26

### PR DESCRIPTION
**Pull request by fennm**

### CODE REVIEW

**Comment by jarun** [comment]
How about having packages for both 24 and 26 in place? We can remove 24 after 1/2 releases.

**Comment by jarun** [comment]
Same goes for nnn.

**Comment by fennm** [comment]
Well Fedora 24 became EOL with the release of Fedora 26, so I don't think it makes sense to continue providing updated packages for it. CentOS 7 is the correct release to use for long term support.

**Comment by jarun** [comment]
Thanks! In that case we are good to go!

**Pull request merged**
