### PR TITLE
Add some info about what's stored in dist

### PR DESCRIPTION
**Pull request by fennm**

### CODE REVIEW

**Comment by jarun** [comment]
I am adding you as a collaborator for better access.

**Comment by fennm** [comment]
Ah, OK thanks!

**Comment by jarun** [comment]
Done!

**Comment by jarun** [comment]
Please use tags below 1.3 (e.g.1.2.1, 1.2.2 ...) so that we can make the next release as 1.3 when this is fixed.

**Comment by jarun** [comment]
Also if we can clean-up the temp RPMs during testing it would be great.

**Comment by fennm** [comment]
For clarification, when you say to clean up the RPMs, you do mean in the releases?

**Comment by jarun** [comment]
Nope, only during the tests when you use temporary tags. We will maintain all released RPMs.

**Comment by jarun** [comment]
Does this help?

http://stackoverflow.com/questions/34227854/error-while-executing-gem-errnoeacces-permission-denied-rb-sysopen

**Comment by fennm** [comment]
Yep, that was it!  Odd that it needs to own the files, one would think world-readilbity would be enough.

**Comment by fennm** [comment]
I went and deleted the pre-release RPMs.  The release ones look good AFAICT.

**Comment by jarun** [comment]
Awesome!

**Pull request merged**
