### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by SompuZ**
Was working if both operands are plain number in case of multiplication. 
i.e. bcal "2kb+3mb/4+5*56mb"
Fixed it.

### CODE REVIEW

**Comment by SompuZ** [comment]
I have a question.
Why did you change fprintf(stdout,) to printf and why were you using that before?

**Comment by jarun** [comment]
Both are same. For errors I intended to use `fprintf(stderr, ...)` so kept it similar. But printf() prints to stdout anyway.

**Comment by jarun** [comment]
Thanks!

**Comment by jarun** [comment]
Now we need test cases.

**Comment by jarun** [comment]
BTW, I tried the earlier tip. The following work even without this patch:

```
bcal "2kb+3mb/4+5*56mb"
bcal "2kb+3mb/4*5+5*56mb"
```

However, the following fails!

```
./bcal "5*5*5mb"
```

Please fix.

**Comment by jarun** [comment]
I have root caused the issue. Working on it.

**Comment by jarun** [comment]
Debug logs help a lot with issues like these.

**Comment by jarun** [comment]
Fixed at #12.

**Comment by jarun** [comment]
@SampuZ when I say debug logs, I already have a debug framework ready in dslib.
When I say test cases, Travis is already integrated, you can add a script, call expressions. You don't even need to calculate the results manually. Search google with the same expression, you'll get the value in the first card search result.

**Pull request merged**
