### PR TITLE
Updated man and readme

### PR DESCRIPTION
**Pull request by SompuZ**
correct spelling in c file help section

### CODE REVIEW

**Comment by jarun** [comment]
Please fix the merge conflicts.

**Comment by jarun** [comment]
You'll have to update your master because I have made some changes too.

**Comment by SompuZ** [comment]
Where the merge conflict is coming from? I am not understanding

**Comment by jarun** [comment]
Update your master to upstream first. I have made many changes in bcal.c.

**Comment by jarun** [comment]
See the diff: https://github.com/jarun/bcal/pull/8/files

**Comment by SompuZ** [comment]
Why the readme is getting conflicts?

**Comment by jarun** [comment]
Then there must be differences between the README in bcal master and yours. Probably copy it from bcal master and put your changes on top of it.

**Comment by jarun** [comment]
In dslib.h, most of the utility functions you are either doing malloc() and returning memory that you never free OR return a local variable. Please fix those leaks.

**Comment by jarun** [comment]
Probably have something like a destroyqueue/stack which would clean up everything.

**Comment by jarun** [comment]
@SampuZ can you discard your current fork and create a fresh fork from bcal master and then make your changes on top of it?

**Comment by SompuZ** [comment]
ok. And in main I think destroy stack/queue is not required as while evaluating the expression, I am already making the stack/queue empty. In postfix conversion function I am filling the queue, and evaluation function I am making the queue empty. Also the local stacks are emptied before function exit. So, why is destroy function required?

**Comment by jarun** [comment]
Are you free()-ing the memory? Then fine.

**Pull request closed without merging**
