### PR TITLE
Travis packages

### PR DESCRIPTION
**Pull request by fennm**
Work in progress to build packages with Travis CI

### CODE REVIEW

**Comment by fennm** [comment]
@jarun I think this is complete for RPM builds at least and the general framework to support any OS with a docker image is in place.

**Comment by jarun** [comment]
Thanks @fennm! Wha's the trigger to generate RPMs? A new tag?

**Comment by fennm** [comment]
@jarun Yes, pushing a new tag "should" cause RPMs to be generated.

**Comment by jarun** [comment]
Thanks for confirming.

**Comment by fennm** [comment]
Thanks!

Michael

**Comment by jarun** [comment]
Thank you! I'll test it and confirm.

**Comment by jarun** [comment]
I am getting this:
https://travis-ci.org/jarun/bcal/jobs/168337096

However the auth key has full repo permissions.

**Pull request merged**
