### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by SompuZ**

### CODE REVIEW

**Comment by jarun** [comment]
Nice! I guess you had some changes in bcal.c and bcal.1 as well. Please add those.

**Comment by jarun** [comment]
Thanks!

**Comment by SompuZ** [comment]
OK. And one problem may be there, when the user enters incorrect inputs, we are just exiting the application showing error message. That time probably the stack and queue is not getting freed.

**Comment by jarun** [comment]
Please fix.

**Comment by jarun** [comment]
Don't forget to update your fork master. I am making several changes.

**Comment by jarun** [comment]
In the following APIs you are returning local objects by value, which you shouldn't. Why not pass it from the caller?

```
Data pop(stack **top)
Data dequeue(queue **front,queue **rear)
```

**Comment by jarun** [comment]
Regarding leaks, rule of the thumb - never use immediate exit(). Show usage(), return error code from the function, free help memory and then quit. The reason is, tomorrow the program flow might change and someone may allocate some intermediate memory which wouldn't be freed due to a rogue exit().

**Comment by jarun** [comment]
Avoid dynamic memory allocation (malloc, calloc, realloc) as much as possible. If you MUST, then the first thing after writing malloc() would be to figure out where to free.

For the current case I would suggest running the code in valgrind and find the leaks. If you want to do it statically use cppcheck or clang static analyzer. The second one would also ensure our code is clang compatible.

**Pull request merged**
